### ISSUE TITLE
error report while launching follow_target

### ISSUE THREAD

**Issue by clebschcrt** [AndrejOrsula/ign_moveit2_examples#22]
after colcon build workspace and source it successfully,when I tried to launch it, as tutorial guides, 
`ros2 launch ign_moveit2_examples ex_py_follow_target.launch.py`
ignition gazebo got crashed and I got these error report.
![Screenshot from 2022-11-17 15-37-15](https://user-images.githubusercontent.com/118234331/202386465-e3f45afc-dc57-4936-a03b-e04224e82753.png)
It confused me.Then I open model.sdf and other sdf file,and change version1.9 to 1.8,but it doesn't work.
Could anyone help me? Deeply  appreciated

**Comment by AndrejOrsula** [comment]
Hello @clebschcrt,

Thank you for opening this issue.
What ROS 2 distribution do you use? This repository was written for `galactic`.

**Comment by AndrejOrsula** [comment]
Closed due to inactivity
