### ISSUE TITLE
how to use the docker

### ISSUE THREAD

**Issue by yunlong12** [AndrejOrsula/ign_moveit2_examples#24]
Thanks for your nice work, which is very useful to me. In your code, I can see there is something about docker, dockerfile, etc. Could you please put some info in the REAMME about how to use docker to run the examples? Thanks.

**Comment by AndrejOrsula** [comment]
Hello, 
You can use the scripts in the [`.docker`](https://github.com/AndrejOrsula/ign_moveit2_examples/blob/aa3704afcb4c6400c32b5780dd404744f4965c7a/.docker) directory. Something like this:

#### Build Image (optional, image is already on [Docker Hub](https://hub.docker.com/repository/docker/andrejorsula/ign_moveit2_examples))

To build a new Docker image from Dockerfile, you can run `build.bash` as shown below.

```bash
.docker/build.bash ${TAG:-latest} ${BUILD_ARGS}
```

#### Run Container

To run the Docker container, you can use `run.bash` as shown below.

```bash
.docker/run.bash ${TAG:-latest} ${CMD}
```

#### Run Dev Container

To run the Docker container in a development mode (source code mounted as a volume), you can use `devel.bash` as shown below.

```bash
.docker/devel.bash ${TAG:-latest} ${CMD}
```
